# Use postgres/postgres user/password credentials
# Database: postgres

services:
  db:
    # Use the pgvector image to enable vector similarity search in PostgreSQL
    image: pgvector/pgvector:pg17-bookworm
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT:-55432}:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - data-db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  data-db:
